definitions:
  util.APIResponse:
    properties:
      data:
        description: 成功时返回业务数据
      meta:
        description: 列表分页、游标等响应元信息
    type: object
info:
  contact: {}
paths:
  /home:
    get:
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/util.APIResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: 健康检测
      tags:
      - Health
swagger: "2.0"
